import 'package:flutter/material.dart';
import 'widgets/report_glass_widgets.dart';

class ProfitLossPage extends StatelessWidget {
  final VoidCallback onBack;
  const ProfitLossPage({super.key, required this.onBack});

  @override
  Widget build(BuildContext context) {
    return _ProfitLossBody(
      title: 'Profit and Loss Statement',
      onBack: onBack,
    );
  }
}

class _ProfitLossBody extends StatelessWidget {
  final String title;
  final VoidCallback onBack;
  final String? notice;

  const _ProfitLossBody({
    required this.title,
    required this.onBack,
    this.notice,
  });

  @override
  Widget build(BuildContext context) {
    return ReportGlassPage(
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ReportTitleBar(
              title: title,
              onBack: onBack,
              showDownloads: true,
            ),
            if (notice != null) ...[
              const SizedBox(height: 18),
              ReportNotice(text: notice!, warning: false),
            ],
            const SizedBox(height: 18),
            const ReportSectionTable(
              rows: [
                ReportRowData('INCOME', '', style: ReportRowStyle.section),
                ReportRowData('Total Revenue', '0.00'),
                ReportRowData('Cost of Goods Sold (COGS)', '(0.00)'),
                ReportRowData('Gross Profit', '0.00', style: ReportRowStyle.subtotal),
                ReportRowData('OPERATING EXPENSES', '', style: ReportRowStyle.section),
                ReportRowData('No expenses recorded', '0.00', indent: true),
                ReportRowData('Total Operating Expenses', '(0.00)', style: ReportRowStyle.subtotal),
                ReportRowData('Net Profit (Operating Income)', '0.00', style: ReportRowStyle.total),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class ProfitLossScheduleIIIPage extends StatelessWidget {
  final VoidCallback onBack;
  const ProfitLossScheduleIIIPage({super.key, required this.onBack});

  @override
  Widget build(BuildContext context) {
    return _ProfitLossBody(
      title: 'Profit and Loss (Schedule III)',
      onBack: onBack,
      notice:
          'Note: This is a simplified Profit & Loss statement based on your available data. A compliant Schedule III report requires a full accounting ledger, which is not present. Missing data includes: Employee Benefits, Finance Costs, Depreciation, and Income Tax.',
    );
  }
}

class HorizontalProfitLossPage extends StatelessWidget {
  final VoidCallback onBack;
  const HorizontalProfitLossPage({super.key, required this.onBack});

  @override
  Widget build(BuildContext context) {
    return _ProfitLossBody(
      title: 'Horizontal Profit and Loss',
      onBack: onBack,
      notice:
          'Note: This report shows a simplified Profit & Loss statement based on your available data (Invoices, Item Purchase Prices, Expenses). It may differ from a report generated by a full accounting system.',
    );
  }
}
